steps:
  # 1. Build do Maven
  - name: 'maven:3-amazoncorretto-21'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'install'
      - '-U'
      
  # 2. Build da Imagem Docker
  - name: 'us-central1-docker.pkg.dev/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/app-imagens/alberguepro:latest'
      - '.'
      
  # 3. Push da Imagem
  - name: 'us-central1-docker.pkg.dev/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/app-imagens/alberguepro:latest'
      
  # 4. Deploy no Cloud Run
  - name: 'us-central1-docker.pkg.dev/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'alberguepro'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/app-imagens/alberguepro:latest'
      - '--region=us-central1'
      - '--platform=managed'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/app-imagens/alberguepro:latest'

timeout: 900s